# Generated by Django 4.2.4 on 2023-09-29 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+79999999999' or '89999999999'.", regex='^((\\+7)|8)\\d{10}$')]),
        ),
    ]
