# Generated by Django 4.2.5 on 2023-10-14 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_enrollment_student_alter_course_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 9, 23, 25, 532517, tzinfo=datetime.timezone.utc)),
        ),
    ]
