# Generated by Django 4.2.4 on 2023-10-03 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-publish']},
        ),
        migrations.AlterField(
            model_name='course',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 13, 19, 52, 389947, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-publish'], name='course_cour_publish_c33f86_idx'),
        ),
    ]
