# Generated by Django 4.2.4 on 2023-10-03 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_options_alter_course_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 15, 48, 32, 272797, tzinfo=datetime.timezone.utc)),
        ),
    ]
