# Generated by Django 4.2.4 on 2023-10-03 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 16, 28, 44, 420822, tzinfo=datetime.timezone.utc)),
        ),
    ]
