# Generated by Django 4.2.5 on 2023-10-04 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_course_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 14, 36, 37, 976207, tzinfo=datetime.timezone.utc)),
        ),
    ]
