# Generated by Django 4.2.5 on 2023-10-05 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_course_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 5, 13, 52, 28, 804757, tzinfo=datetime.timezone.utc)),
        ),
    ]
