# Generated by Django 4.2.5 on 2023-10-08 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_course_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 6, 53, 40, 838098, tzinfo=datetime.timezone.utc)),
        ),
    ]
